import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import Header from "../components/Header";
import Footer from "../components/Footer";
import AppMotionWrapper from "./_app-motion-wrapper";

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased bg-diner-cream`}>
        <Header />
        <main className="min-h-[70vh] flex flex-col items-center justify-center w-full">
          <AppMotionWrapper>
            {children}
          </AppMotionWrapper>
        </main>
        <Footer />
      </body>
    </html>
  );
}
